services:
  app:
    container_name: easy-coast
    restart: unless-stopped
    build:
      context: .
      target: ${DOCKER_BUILD_STAGE:-prod}
    develop:
      watch:
        - path: ./src/
          target: /app/src
          action: sync+restart
        - path: ./pom.xml
          target: /app/pom.xml
          action: rebuild
    depends_on:
      - database
    networks:
      easycoast:
    ports:
      - ${APP_PORT:-8080}:8080
    volumes:
      - mvn_deps:/root/.m2

  database:
    image: docker.io/library/postgres:18-alpine
    container_name: ${POSTGRES_HOST:-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste01@}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-easy_coast}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - database:/var/lib/postgresql
    networks:
      easycoast:

volumes:
  database:
  mvn_deps:

networks:
  easycoast:
    driver: bridge
