services:
  app:
    container_name: app
    restart: unless-stopped
    build:
      context: .
      target: ${DOCKER_BUILD_STAGE:-prod}
    develop:
      watch:
        - path: ./src/
          target: /app/src
          action: sync+restart
        - path: ./pom.xml
          target: /app/pom.xml
          action: rebuild
    depends_on:
      database:
        required: true
        condition: service_healthy
        restart: false
    networks:
      - easycoast
    ports:
      - ${APP_PORT:-8080}:8080
    volumes:
      - mvn_deps:/root/.m2
    healthcheck:
      test: "wget -T5 -qO- http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  database:
    image: docker.io/library/postgres:18-alpine
    container_name: ${POSTGRES_HOST:-postgres}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-teste01@}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-easy_coast}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - database:/var/lib/postgresql
    networks:
      - easycoast
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  database:
    name: backend-pi-database
  mvn_deps:
    name: backend-pi-mvn-deps

networks:
  easycoast:
    name: easycoast
    driver: bridge
