INSERT INTO TBL_RESTAURANT (NAME, LOCATION, WHO_ARE_WE, SEATS) VALUES ('Polvo Provençal', 'R. tal tal', 'Um ótimo restaurante', 7);

INSERT INTO TBL_SQUARES (NAME, DELETED) VALUES ('Frituras', false);
INSERT INTO TBL_SQUARES (NAME, DELETED) VALUES ('Assados', false);
INSERT INTO TBL_SQUARES (NAME, DELETED) VALUES ('Bebidas', false);

INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Arroz', 1, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Feijão', 1, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Macarrão', 1, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Azeitonas', 1, false);

INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Frango Frito', 2, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Filé Mignon', 2, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Picanha', 2, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Peixe', 2, false);

INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Cerveja', 3, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Refrigerante', 3, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Suco', 3, false);
INSERT INTO TBL_ITEM (NAME, SQUARE_ID, DELETED) VALUES ('Água', 3, false);

INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 
INSERT INTO TBL_SEAT (STATUS) VALUES (0); 

INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (true, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 2);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (true, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 2);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (true, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 2);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (true, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 2);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (true, 1);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 2);
INSERT INTO TBL_CARDS (ACTIVE, COPY) VALUES (false, 1);

INSERT INTO TBL_EMPLOYEE (NAME, LOGIN, PHONE, PASSWORD, PROFILE, BLOCKED, DELETED)
VALUES ('Jorge Silva', 'jorge@email.com', '100001030', '1234', 2, FALSE, FALSE);

INSERT INTO TBL_EMPLOYEE (NAME, LOGIN, PHONE, PASSWORD, PROFILE, BLOCKED, DELETED)
VALUES ('Marina Costa', 'marina@email.com', '100001031', '3213', 0, TRUE, FALSE);

INSERT INTO TBL_EMPLOYEE (NAME, LOGIN, PHONE, PASSWORD, PROFILE, BLOCKED, DELETED)
VALUES ('Rafael Lima', 'rafael@email.com', '100001032', '483827', 2, FALSE, FALSE);

INSERT INTO TBL_CATEGORY (NAME, AVAILABILITY, DELETED) VALUES ('Nome qualquer', true, false);

INSERT INTO TBL_SUBCATEGORY (NAME, AVAILABILITY, CATEGORY_ID, DELETED) VALUES ('Bebidas', true,  1, false );
INSERT INTO TBL_SUBCATEGORY (NAME, AVAILABILITY, CATEGORY_ID, DELETED) VALUES ('Prato Principal', false,  1, false );
INSERT INTO TBL_SUBCATEGORY (NAME, AVAILABILITY, CATEGORY_ID, DELETED) VALUES ('Sobremesa', true,  1, false );

INSERT INTO TBL_PRODUCT (name, description, price, discount, availability, SUBCATEGORY_ID, imageUrl, DELETED)
VALUES ('Pizza Margherita', 'Pizza com molho de tomate, mussarela e manjericão fresco', 39.90, 0.0, TRUE, 1, 'https://abrir.link/gSCkw', false);
INSERT INTO TBL_PRODUCT (name, description, price, discount, availability, SUBCATEGORY_ID, imageUrl, DELETED)
VALUES ('Hambúrguer Artesanal', 'Pão brioche, carne Angus, queijo cheddar e molho especial', 29.90, 5.0, TRUE, 2, 'https://abrir.link/WrIHG', false);
INSERT INTO TBL_PRODUCT (name, description, price, discount, availability, SUBCATEGORY_ID, imageUrl, DELETED)
VALUES ('Salada Caesar', 'Alface americana, croutons, frango grelhado e molho caesar', 24.90, 10.0, TRUE, 3 , 'https://abrir.link/rbVqV', false);

INSERT INTO TBL_ADDONCATEGORY (NAME, TYPE, PRODUCT_ID, DELETED) VALUES ('Molhos Extras', 1, 3, false);
INSERT INTO TBL_ADDONCATEGORY (NAME, TYPE, PRODUCT_ID, DELETED) VALUES ('Adicionais do Hambúrguer', 0, 2, false); 
INSERT INTO TBL_ADDONCATEGORY (NAME, TYPE, PRODUCT_ID, DELETED) VALUES ('Recheios Extras', 1, 1, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Molho Caesar Extra', 3.50, TRUE, 3, 1, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Parmesão Ralado', 2.00, TRUE, 3, 1, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Bacon Crocante', 4.00, TRUE, 2, 2, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Ovo Frito', 3.00, TRUE, 2, 2, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Recheio de Calabresa', 5.00, TRUE, 1, 3, false);

INSERT INTO TBL_ADDON (NAME, PRICE, AVAILABILITY, SQUARE_ID, ADDONCATEGORY_ID, DELETED)
VALUES ('Recheio de Catupiry', 5.00, TRUE, 1, 3, false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('John Doe', '100001020', '2000-11-25T00:00:00Z', 'johndoe@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Alice Smith', '100001021', '1995-08-15T00:00:00Z', 'alice.smith@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Carlos Mendes', '100001022', '1988-04-03T00:00:00Z', 'carlos.mendes@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Bruna Oliveira', '100001023', '1992-12-30T00:00:00Z', 'bruna.oliveira@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Daniel Costa', '100001024', '1990-07-10T00:00:00Z', 'daniel.costa@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Fernanda Lima', '100001025', '1998-03-22T00:00:00Z', 'fernanda.lima@gmail.com', false);

INSERT INTO TBL_CUSTOMER (NAME, PHONE, BIRTHDATE, EMAIL, DELETED)
VALUES ('Igor Santos', '100001026', '1985-09-17T00:00:00Z', 'igor.santos@gmail.com', false);



INSERT INTO TBL_ORDER (OPENING_TIME, CLOSING_TIME, TOTAL, CARD_ID, SEAT_ID, EMPLOYEE_ID)
VALUES ('1992-12-30 00:00:00', '1992-12-30 01:30:00', 49.99, 1, 5, 2);

INSERT INTO TBL_ORDER (OPENING_TIME, CLOSING_TIME, TOTAL, CARD_ID, SEAT_ID, EMPLOYEE_ID)
VALUES ('2023-05-01 18:15:00', '2023-05-01 19:45:00', 82.50, 2, 3, 1);

INSERT INTO TBL_ORDER (OPENING_TIME, CLOSING_TIME, TOTAL, CARD_ID, SEAT_ID, EMPLOYEE_ID)
VALUES ('2023-05-02 12:00:00', '2023-05-02 13:10:00', 36.20, 3, 1, 2);

INSERT INTO TBL_ORDER (OPENING_TIME, CLOSING_TIME, TOTAL, CARD_ID, SEAT_ID, EMPLOYEE_ID)
VALUES ('2023-05-03 20:00:00', '2023-05-03 21:30:00', 105.75, 4, 4, 3);

INSERT INTO TBL_ORDER (OPENING_TIME, CLOSING_TIME, TOTAL, CARD_ID, SEAT_ID, EMPLOYEE_ID)
VALUES ('2023-05-04 14:30:00', '2023-05-04 15:50:00', 60.00, 5, 2, 1);


-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-04 14:30:00', 21, 1, 1);

-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-04 16:00:00', 15, 2, 2);

-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-05 10:00:00', 12, 3, 3);

-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-06 09:30:00', 20, 4, 4);

-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-07 18:00:00', 17, 5, 5);

-- INSERT INTO TBL_SCHEDULING (STARTS_AT, QUANTITY, CUSTOMER_ID, SEAT_ID) 
-- VALUES ('2023-05-08 13:15:00', 25, 6, 6);
